FROM node:20-alpine AS build-stage

WORKDIR /app

COPY package.json /app/

RUN npm install

COPY ./.. .

ENV REACT_APP_NAME=ER-RM

RUN npm run build

FROM nginx:alpine
COPY --from=build-stage /app/dist/ /usr/share/nginx/html
